### DISCUSSION TITLE
[HELP] Dashboards not listed/downloaded

### DISCUSSION THREAD

**Discussion by bahmanm** [esnet/gdg#200] [Q&A (Help Section)] [answered]
I'm using v0.5.0 with a simple config file as below:

```yaml
context_name: testing

contexts:
  testing:
    output_path: _build/gdg
    url: http://localhost:3000
    user_name: admin
    password: admin
    ignore_filters: true

global:
  debug: true
  ignore_ssl_errors: true
```

I can list connections, users, organisations, etc except dashboards!

What could be missing?

**Comment by csg33k** [comment]
I'm going to convert this to a conversation, as it's likely not a bug or issue with GDG.

**Comment by safaci2000** [comment, marked as answer]
A few questions.  What folder are they in?  By default GDG is very conservative on what it touches.  Initial design was to only look at the list of `watched` folders.  If you don't define any it'll only look at `General`.  

```yaml
    filter_override:
      ignore_dashboard_filters: false # When set to true all Watched filtered folders will be ignored and ALL folders will be acted on
    watched:
      - General
      - Other
```

The snippet below might need to be added depending on what you're setup looks like.  Look at https://github.com/esnet/gdg/blob/master/config/importer-example.yml it has some more complex examples if you need inspiration.

Also, I think the "ignore_filters" you're trying to set isn't a valid configuration option.  If you can let me know where you got that from I'll be sure to remove / update the documentation.

**Reply by bahmanm** [reply]
Let me try that and get back to you.

**Reply by bahmanm** [reply]
That was it!  Thanks for the help :pray: 

---

For posterity, here's the working config:

```yaml
context_name: testing

contexts:
  testing:
    output_path: _build/gdg
    url: http://localhost:3000
    user_name: admin
    password: admin
    filter_override:
      ignore_dashboard_filters: false
    watched:
      - MY FOLDER NAME

global:
  debug: true
  ignore_ssl_errors: true
```
