### DISCUSSION TITLE
[HELP] downloading fails w/ `invalid cross-device link`

### DISCUSSION THREAD

**Discussion by bahmanm** [esnet/gdg#201] [Q&A (Help Section)] [answered]
_I'm testing out gdg to see if I can use it in [my hobby project](/bahmanm/lemmy-meter)._

---

I've got a simple config as below:

```yaml
context_name: testing

contexts:
  testing:
    output_path: _build/gdg
    url: http://localhost:3000
    user_name: admin
    password: admin
    filter_override:
      ignore_dashboard_filters: false
    watched:
      - Instance Health

global:
  debug: true
  ignore_ssl_errors: true
```

I can list all the resources in Grafana w/o any problems.  However I don't seem to be able to download any resource as all of them fail w/ the infamous `invalid cross-device link`.

For example:

```text
gdg backup dashboards download
ERRO[0000] blob (key "instance-health-breakdown.json") (code=Unknown): rename /tmp/instance-health-breakdown.json.1789b080b87ecfd2.tmp /home/bahman/workspace/lemmy-meter/lemmy-meter/_build/gdg/org_1/dashboards/Instance Health/instance-health-breakdown.json: invalid cross-device link for instance-health-breakdown 
ERRO[0000] blob (key "lemmy-meter-info.json") (code=Unknown): rename /tmp/lemmy-meter-info.json.1789b080bab9dd6c.tmp /home/bahman/workspace/lemmy-meter/lemmy-meter/_build/gdg/org_1/dashboards/Instance Health/lemmy-meter-info.json: invalid cross-device link for lemmy-meter-info 
INFO[0000] Importing dashboards for context: 'testing'  
┌──────┬──────────┐
│ TYPE │ FILENAME │
├──────┼──────────┤
└──────┴──────────┘
```

---

Do you think this is a configuration issue?  Have I missed anything obvious?
