### DISCUSSION TITLE
Add Support for running backup as K8s CRONJOB

### DISCUSSION THREAD

**Discussion by kisermichael** [esnet/gdg#245] [Q&A (Help Section)] [answered]
**Is your feature request related to a problem? Please describe.**
Would like the ability to be able to backup dashboards on a nightly basis thru the use of a K8s CRONJOB.

**Describe the solution you'd like**
Would like to see an example K8s CRONJOB and associated templates become part of the repo.

**Describe alternatives you've considered**
We can run the backup manually but would like to be able to specify a specific time to have it run.

**Additional context**
N/A

**Comment by safaci2000** [comment]
This is a bit out of scope of this project and it's constantly, changing, if you like to do a PR, feel free to do so.

Based on quick google it would be something like this.  

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ghcr.io/esnet/gdg:0.5.2
            imagePullPolicy: IfNotPresent
            command:
            - backup
            - download 
            - -d 
            - transform-monitoring  
          restartPolicy: OnFailure
```

Additionally you probably need to mount the configuration from a volume mount or expose various .ENV values to configure the app.  You'd need a volume for where your backups go ie. exports or configure GCS/S3 etc destinations.

See link below for more context:    https://stackoverflow.com/questions/46578331/kubernetes-is-it-possible-to-mount-volumes-to-a-container-running-as-a-cronjob
