### DISCUSSION TITLE
Example to costruct a secureJsonFields

### DISCUSSION THREAD

**Discussion by sureshoss** [esnet/gdg#253] [Q&A (Help Section)] [answered]
Its little unclear how we can add the secureJsonFields to teh Datasources when downloaded from the grafana server with the secure_data json file from the secure directory, tried multiple options but still could not get it working, is there someone that has already worked on this and sharing a importer.yml sample and a sample of json from the secure directory with custom fields to be secured for some datasources would be realy helpful

**Comment by safaci2000** [comment, marked as answer]
hello @sureshoss 

The secure data is sensitive data so the Grafana API will never let you download that information.  Same for user passwords etc.


https://software.es.net/gdg/docs/gdg/configuration/#connection has an example of what the secureData looks like.  

There's also some example files here:  https://github.com/esnet/gdg/tree/master/test/data/secure

If we're using the test data as an example, I have two possible Auth I can use, complex.json and default.json.

So in my configuration

```yaml
contexts:
  testing:
    output_path: test/data
    connections:
      credential_rules:
        - rules:
            - field: "name"
              regex: "misc"
            - field: "url"
              regex: ".*esproxy2*"
          secure_data: "complex.json"
        - rules:
            - field: "name"
              regex: ".*"
          secure_data: "default.json"
    url: http://localhost:3000
```    

Here's the standard secureData:
```json
{
    "basicAuthPassword": "password",
    "user": "user"
}
```

There's a lot more fields you can pass but that varies on the connection type etc that you have.  

---

As You can see that secure_data references the file_name that lives inside your `exports/secure` folder

You can also get a really simple example configured using the context wizard:

```sh
./bin/gdg tools ctx new  example    
```
That will walk you through a very basic CLI wizard to configure a connection, setup your secure/default.json that is referenced by default.
