### DISCUSSION TITLE
[BUG] gdg backup

### DISCUSSION THREAD

**Discussion by LuckySB** [esnet/gdg#297] [Q&A (Help Section)]
`gdg backup dash download` get dashboards only from folder *General*

**Describe the bug**
A clear and concise description of what the bug is.  If applicable and possible the JSON of dashboard or datasource that is causing issues with credentials removed would be helpful.

**To Reproduce**
Create dashboard1 in folder General
Create *new folder* in grafana, create dashboard2 in this new folder

`gdg backup dash list` - show dashboard only in folder General
`gdg backup dash download` - download dashboard only from folder Geneatl

to download dashboard from *new folder* must be set -f
`gdg backup dash download -f 'new folder'`

**Expected behavior**

`gdg backup dash download` - should be download dashboards from all folder

**Desktop (please complete the following information):**
 - GDG Version: 0.6.0
 - Grafana Version: 9.5.2
 - Configuration for Importer
```
context_name: main

contexts:
  main:
    url: https://grafana
    token: "glsa_...."
    output_path: "myFolder"
```
