### ISSUE TITLE
Need a way to provide more complex credential to datasource mapping

### ISSUE THREAD

**Issue by safaci2000** [esnet/gdg#146]
**Is your feature request related to a problem? Please describe.**

Currently the datasource credentials are either using:   name matching (aka match auth based on the DS label), falling back on default auth OR using a regex matching against a specific URL.

We now have a use case where given the same auth, same URL, we'd like to use a different set of credentials based on a different index name (for elasticsearch).

Ideally there should be a more generic mapping for given property or pseudo logic that we could embed in a CFG to be executed. 

**Describe the solution you'd like**

Since all of these operations is performed on a JSON object (aka a DS payload) that was saved from Grafana.

the enhanced regex which would also deprecated the previous URL mapping would 1 or more validation rules all which are a list of tuples.

1: json_path :   "jsonData.esVersion"  (Supported pattern based on: https://github.com/tidwall/gjson ) 
   regexPattern:  "8.*"   (Any valid GoLang support Regex) 

Changing from:

```yaml
 datasources:
      credentials:
        complex name:
          password: secret
          user: test
        default:
          password: password
          user: user
        ds_name:
          password: secret
          user: abcd
```

to 

```yaml
datasources:
   credential_rules:
       - rules:
              - field:  "name"
                 regex:  "DS Name"
              - field: "url"
                 regex: https://192.168.23.* 
          auth: 
                username:  abcd
                password: 13242
  ## default rule              
       - rules:
              - field:  "name"
                 regex:  "*.*"
          auth: 
                username:  admin
                password: admin
```

**Describe alternatives you've considered**

**Additional context**
