### ISSUE TITLE
[HELP] Dashboards not listed/downloaded

### ISSUE THREAD

**Issue by bahmanm** [esnet/gdg#199]
I'm using v0.5.0 with a simple config file as below:

```yaml
context_name: testing

contexts:
  testing:
    output_path: _build/gdg
    url: http://localhost:3000
    user_name: admin
    password: admin
    ignore_filters: true

global:
  debug: true
  ignore_ssl_errors: true
```

I can list connections, users, organisations, etc except dashboards!

What could be missing?
