### ISSUE TITLE
[BUG] Cannot upload node exporter dashboard

### ISSUE THREAD

**Issue by kossioni** [esnet/gdg#226]
**Describe the bug**
I have used gdg to download a provisioned dashboard. Then removed the provisioned folder contents and restarted grafana. Used gdg to upload the downloaded dashboard and I get:

`
```
kossioni@kossioni-3 backup % docker run -it --name grafanaDashNGrab-restore-dashboards --rm --network host -v $(pwd)/config:/app/config -v $(pwd)/exports:/app/exports ghcr.io/esnet/gdg:latest backup dashboards upload                     
WARNING: this will delete all dashboards from the monitored folders: 'General, Koko' (or all folders if ignore_dashboard_filters is set to true) and upload your local copy.  Do you wish to continue (y/n) y
DEBU[0000] Folder name is: General                      
DEBU[0000] Folder name is: General                      
INFO[0000] error on Exporting dashboard /app/exports/org_1/dashboards/General/node-exporter-full.json  error="<nil>"
DEBU[0000] Folder name is: Koko                         
┌─────────────────────────────────┬────┬─────────┬──────────────────────────────────────┐
│ TITLE                           │ ID │ FOLDER  │ UID                                  │
├─────────────────────────────────┼────┼─────────┼──────────────────────────────────────┤
│ Docker Container & Host Metrics │ 19 │ General │ 4dMaCsRZz                            │
│ Papas                           │ 20 │ Koko    │ a4842c40-e94f-4ba9-8978-89a849961f2a │
└─────────────────────────────────┴────┴─────────┴──────────────────────────────────────┘
```
`

I am attaching the dashboard: [node-exporter-full.json](https://github.com/esnet/gdg/files/13377454/node-exporter-full.json)

How can I avoid the <nil> error?

**Expected behavior**
The dashboard should be imported successfully.

**Desktop (please complete the following information):**
 - GDG Version: [0.5.1]
 - Grafana Version: [10.0.2] 
 - Configuration for Importer

```
context_name: onpremGrafana
storage_engine:
    any_label:
        bucket_name: ""
        cloud_type: s3
        kind: cloud
    custom_cloud:
        access_id: ""
        bucket_name: mybucket
        cloud_type: s3
        custom: "1"
        endpoint: http://localhost:9000
        init_bucket: "true"
        kind: cloud
        prefix: dummy
        secret_key: ""
        ssl_enabled: "false"
contexts:
    onpremGrafana:
        storage: ""
        enterprise_support: false
        url: http://localhost:3000
        token: ""
        user_name: admin
        password: Admin4Grafana
        organization_id: 1
        watched_folders_override: []
        watched:
            - General
            - Koko
        connections: {}
        datasources: {}
        filter_override:
          ignore_dashboard_filters: false
        output_path: /app/exports
    azureGrafana:
        storage: ""
        enterprise_support: false
        url: https://10.120.88.39
        token: "xxx"
        organization_id: 0
        watched_folders_override: []
        watched:
            - General
            - ACE
            - DevOps
            - Elastic
            - Github
            - Istio
            - Jenkins
            - MQ
            - Nexus
            - Openshift
            - Openshift-CBSCL
            - Openshift-OCPC
            - Operations
            - Oracle
            - Performance
            - Redis
            - Sonarqube
            - System
            - TEST-Stathis
            - UCV_UCD
            - Windows
        connections: {}
        datasources: {}
        filter_override:
          ignore_dashboard_filters: false
        output_path: /app/exports
global:
    debug: true
    ignore_ssl_errors: true
```

**Comment by safaci2000** [comment]
I haven't seen this behavior before, but just want to check.  When I do this manually in grafana, it doesn't let me import the dashboard unless the data source exists.  Did you import the Prometheus connection before the dashboard?

**Comment by safaci2000** [comment]
Actually, this is the error I get from grafana.

```
logger=context userId=1 orgId=1 uname=admin t=2023-11-16T15:15:57.689596349Z level=error msg="Failed to save dashboard" error="Dashboard input variable: DS_PROMETHEUS missing from import command" remote_addr=172.18.0.1 traceID=
```

**Comment by kossioni** [comment]
The datasource/connection was already imported and in place beforehand. If I remove from the dashboard the top section then I can import it using gdg:

```
"__elements": {},
  "__inputs": [
    {
      "description": "",
      "label": "Prometheus",
      "name": "DS_PROMETHEUS",
      "pluginId": "prometheus",
      "pluginName": "Prometheus",
      "type": "datasource"
    }
  ],
  "__requires": [
    {
      "id": "gauge",
      "name": "Gauge",
      "type": "panel",
      "version": ""
    },
    {
      "id": "grafana",
      "name": "Grafana",
      "type": "grafana",
      "version": "9.4.3"
    },
    {
      "id": "prometheus",
      "name": "Prometheus",
      "type": "datasource",
      "version": "1.0.0"
    },
    {
      "id": "stat",
      "name": "Stat",
      "type": "panel",
      "version": ""
    },
    {
      "id": "timeseries",
      "name": "Time series",
      "type": "panel",
      "version": ""
    }
  ],
```

This is the stock node exporter dashboard from grafana: https://grafana.com/grafana/dashboards/1860-node-exporter-full/

**Comment by kossioni** [comment]
<img width="1070" alt="image" src="https://github.com/esnet/gdg/assets/101812286/05a4a36b-3df1-494f-b4ac-bff9f2bedf00">
You are right this is a problem this the backup see above picture!

**Comment by kossioni** [comment]
Replication details:

Try with docker-compose.yml:

```
version: "3.4"

services:
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:10.2.0
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Admin4Grafana
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=true
      - GF_AUTH_GOOGLE_OAUTH_TLS_SKIP_VERIFY_INSECURE=true
      - GF_AUTH_GRAFANANET_TLS_SKIP_VERIFY_INSECURE=true
      - GF_AUTH_GRAFANA_COM_TLS_SKIP_VERIFY_INSECURE=true
      - GF_PLUGINS_APP_TLS_SKIP_VERIRY_INSECURE=true
      - GF_SMTP_ENABLED=false
      - GF_DATABASE_WAL=true
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./dashboards:/var/lib/grafana/dashboards
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus-central
    restart: unless-stopped
```

datasource.yml:

```
# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
- name: Prometheus
  orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
# <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://prometheus-central:9090
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  # <string> database name, if used
  database:
  # <bool> enable/disable basic auth
  basicAuth: false
  # <string> basic auth username, if used
  basicAuthUser:
  # <string> basic auth password, if used
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
```

main.yaml:

apiVersion: 1

```
providers:
- name: "Dashboard provider"
  orgId: 1
  type: file
  disableDeletion: true
  updateIntervalSeconds: 10
  allowUiUpdates: true
  options:
    path: /var/lib/grafana/dashboards
    foldersFromFilesStructure: true
```

In ./dashboards put the stock node exporter dashboard download from [here](https://grafana.com/grafana/dashboards/1860-node-exporter-full/)
