### ISSUE TITLE
[BUG] ignore_dashboard_filters is not giving any dashboard

### ISSUE THREAD

**Issue by paulojmdias** [esnet/gdg#232]
**Describe the bug**
When we try to set `ignore_dashboard_filters: false` the gdg is not finding any dashboard. When we set `ignore_dashboard_filters: true`, he founds everything.

**Config** 

```yaml
context_name: grafana
storage_engine:
  s3:
    access_id: REDACTED
    bucket_name: grafana
    cloud_type: s3
    custom: "1"
    endpoint: http://localhost:9000
    kind: cloud
    secret_key: REDACTED
    self_hosted: "1"
    ssl_enabled: "0"
contexts:
  grafana:
    storage: s3
    enterprise_support: false
    url: http://localhost:3000
    token: ""
    user_name: REDACTED
    password: REDACTED
    organization_id: 0
    watched_folders_override: []
    watched: []
    connections: null
    datasources: {}
    filter_override:
      ignore_dashboard_filters: false
    output_path: ""
  grafana1:
    storage: s3
    enterprise_support: false
    url: http://localhost:3001
    token: ""
    user_name: REDACTED
    password: REDACTED
    organization_id: 0
    watched_folders_override: []
    watched: []
    connections: null
    datasources: {}
    filter_override:
      ignore_dashboard_filters: false
    output_path: ""
global:
  debug: true
  ignore_ssl_errors: false

```

**To Reproduce**
```sh
❯ gdg backup dashboards list --skip-confirmation --config config.yml
INFO[0000] Listing dashboards for context: 'grafana'
INFO[0000] No dashboards found
```

**Expected behavior**
Even with `ignore_dashboard_filters: false` the gdg should search on all folders when `watched` is empty.

**Desktop (please complete the following information):**
 - GDG Version: 0.5.1
 - Grafana Version: 10.2.2

**Additional context**
Let me explain better our end goal:
- We want to backup all dashboards with a specific tag(s) to an S3 bucket
- We want to sync multiple grafana deployments from this S3 bucket depending on conditions (In this step, we can't filter on upload right?)

Explaining better the upload process:
- For example, let's imagine the `dashboardA` has the tags `prd` and `qa`, this dashboard should be uploaded in these two environments
- Let's imagine the `dashboardB` has the tag `prd`, this dashboard should be deployed only in `prd` context, this is possible to be done?
