### ISSUE TITLE
[BUG] gdg backup dashboard {upload, clear} does not work on Granfana 10.2.2

### ISSUE THREAD

**Issue by tpanum** [esnet/gdg#237]
**Describe the bug**
After running `gdg backup dashboard download`, `gdg backup dashboard clear` does not delete existing dashboards nor is `gdg backup dashboard upload` capable of uploading any dashboards.

**To Reproduce**
1. Have a running Grafana instance version `10.2.2` with some dashboards
2. Run `gdg backup dashboard clear`
```shell
$ gdg backup dashboards clear
INFO[0000] 1 dashboards were deleted                    
┌───────────┬──────────┐
│ TYPE      │ FILENAME │
├───────────┼──────────┤
│ dashboard │ Test     │
└───────────┴──────────┘
```
3. See the dashboard still exists
4. Run `gdg backup dashboard upload`
5. See no dashboards have been uploaded

**Expected behavior**
Expected to be able to delete and upload dashboard on Grafana version `10.2.2`.

**Desktop (please complete the following information):**
 - GDG Version: `0.5.1`
 - Grafana Version: `10.2.2`
 - Configuration for Importer

```yaml
context_name: main

contexts:
  main:
    url: http://localhost
    user_name: admin
    password: admin
    output_path: "grafana-exports"

global:
debug: true
ignore_ssl_errors: true
```
