### ISSUE TITLE
[BUG] Dashboards moved to another folder are not deleted from storage

### ISSUE THREAD

**Issue by arnecls** [esnet/gdg#325]
**Describe the bug**

When a dashboard is moved to another folder, a file with a different name is being created when creating a backup.
However, the old file will not be removed, leading to errors during import.

It has to be noted that we use GCS as a storage.

**To Reproduce**

- We use GCS as a remote storage
- Create a dashboard
- Create a backup
- Move the dashboard
- Create another backup

You will see that the dashboard is now existing twice in GCS with two different filenames.
This leads to an error during restore `Board with same UID was already processed.`

**Expected behavior**

The old file should be deleted.

**Debugging Data (please complete the following information):**

1. gdg version
   
```sh
0.7.1
```

2. gdg tools devel srvinfo  (If you are able to connect to your grafana instance)
   
```sh
2024-12-19 09:12:06 INF  Database=ok
2024-12-19 09:12:06 INF  Commit=5b85c4c2
2024-12-19 09:12:06 INF  Version=11.1.0
```

3. Redacted output of: gdg tools contexts show  (Or include your config )
   
```yaml
storage: gcs
url: ***
token: ""
user_name: ***
password: ***
organization_name: trivago
watched_folders_override: []
watched: []
connections: null
user: null
dashboard_settings:
    nested_folders: false
    ignore_filters: true
output_path: backup
```
