### ISSUE TITLE
Credentials set in Environment variables are written back to config file

### ISSUE THREAD

**Issue by sureshsubramaniam** [esnet/gdg#407]
HI,
We tried to leverage the environment variables for various contexts and it works as expected, however after setting the environment variables and running the commands it writes the set username and password from the environment variable into the config file, how can we avoid having them written to the configuration file for GDG.

**Comment by safaci2000** [comment]
That is a very interesting bug. I’m not able to reproduce it, so maybe you can provide some more insight on how you’re able to get this behavior.  Version and such would be great. 

Here’s some basic testing I’ve done.

 GDG_CONTEXTS__TESTING__USER_NAME="moo" gdg tools ctx show
```
---testing:
token: ""
connections: null
dashboard_settings:
    nested_folders: false
    ignore_filters: true
    ignore_bad_folders: false
watched: []
watched_folders_override: []
organization_name: ""
output_path: test/data
password: admin
storage: ""
url: http://localhost:3000
user_name: moo
user:
    random_password: true
    min_length: 8
    max_length: 20
```

GDG_CONTEXTS__TESTING__USER_NAME="moo" gdg b dash list  (response make sense it’s the wrong password)
```
Unable to retrieve current organization, err: [GET /org][401] getCurrentOrgUnauthorized {"message":"Invalid username or password"}
```

gdg b dash list
```
2025-04-12 10:44:51 INF Running Sanity Check of Organization Membership
2025-04-12 10:44:51 INF Listing dashboards for context context=testing orgName="Main Org." count=0
2025-04-12 10:44:51 INF No dashboards found
```

cat config/importer.yml

```yaml
context_name: testing
storage_engine:
    any_label:
        bucket_name: ""
        cloud_type: s3
        kind: cloud
    custom_cloud:
        access_id: test
        bucket_name: mybucket
        cloud_type: custom
        endpoint: http://localhost:9000
        init_bucket: "true"
        kind: cloud
        secret_key: secretsss
        ssl_enabled: "false"
contexts:
    testing:
        connections: null
        dashboard_settings:
            nested_folders: false
            ignore_filters: true
            ignore_bad_folders: false
        watched: []
        watched_folders_override: []
        output_path: test/data
        user_name: admin
        password: admin
        storage: ""
        url: http://localhost:3000
        user:
            random_password: true
            min_length: 8
            max_length: 20
global:
    debug: false
    api_debug: false
    ignore_ssl_errors: false
    retry_count: 3
    retry_delay: 5s
    clear_output: true

```

All my iterations didn’t modify the password in the actual config.  If you use the “tools context” to copy/set etc  you might get that behavior but those are really just convenience mechanism. You can clear those values out and basic CRUD operations should not affect the config file.  Or avoid using that tooling. I’ll see if I can update the tools to avoid loading the ENV, but originally they were intended to show me what the actual config was, so it’s importer.yml + ENV value = output.  


Please let me know where you’re running into your issue.
